# Generated by Django 5.0.3 on 2024-03-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='accesstoken',
            field=models.CharField(default='charField', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='mail',
            field=models.IntegerField(default=0),
        ),
    ]
