# Generated by Django 5.0.3 on 2024-03-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_accesstoken_blog_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='accesstoken',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mail',
            field=models.CharField(max_length=200),
        ),
    ]
